=== ahaskell83/xml/pubmed-tfm-xml/articles.dtd
<!ELEMENT Publications (Article)>    
    <!ELEMENT Article (PubDetails)>
        <!ATTLIST Article PMID CDATA #REQUIRED>
        <!ELEMENT PubDetails (Journal,ArticleTitle,AuthorList)>
            <!ELEMENT Journal (ISSN,JournalIssue,Title,ISOAbbreviation)>
            <!ELEMENT ISSN (#PCDATA)>
                <!ATTLIST ISSN IssnType CDATA #IMPLIED>
            <!ELEMENT JournalIssue (Volume,Issue,PubDate)>
                <!ATTLIST JournalIssue CitedMedium CDATA #IMPLIED>
                <!ELEMENT Volume (#PCDATA)>
                <!ELEMENT Issue (#PCDATA)>
                <!ELEMENT PubDate (Year,Month)>
                <!ELEMENT Year (#PCDATA)>
                <!ELEMENT Month (#PCDATA)>
                <!ELEMENT Day (#PCDATA)>
                <!ELEMENT MedLineDate (#PCDATA)>
            <!ELEMENT Title (#PCDATA)>
            <!ELEMENT ISOAbbreviation (#PCDATA)>
            <!ELEMENT ArticleTitle (#PCDATA)>
            <!ELEMENT AuthorList (Author*)>
                <!ATTLIST AuthorList CompleteYN CDATA #REQUIRED>
                <!ELEMENT Author (LastName,ForeName,Initials)>
                    <!ATTLIST Author ValidYN CDATA #REQUIRED>
                    <!ELEMENT LastName (#PCDATA)>
                    <!ELEMENT ForeName (#PCDATA)>
                    <!ELEMENT Initials (#PCDATA)>
                    <!ELEMENT Suffix (#PCDATA)>

=== ahaskell83/xml/pubmed-tfm-xml/pubmed-sample.xml
<?xml version="1.0" encoding="UTF-8", standalone="no" ?>
<!DOCTYPE Publications SYSTEM "http://raw.githubusercontent.com/ahaskell83/xml/main/pubmed-tfm-xml/articles.dtd">
<Publications>
  <Article PMID="1">
    <PubDetails>
      <Journal>
        <ISSN IssnType="Print">0006-2944</ISSN>
        <JournalIssue CitedMedium="Print">
          <Volume>13</Volume>
          <Issue>2</Issue>
          <PubDate>
            <Year>1975</Year>
            <Month>Jun</Month>
          </PubDate>
        </JournalIssue>
        <Title>Biochemical medicine</Title>
        <ISOAbbreviation>Biochem Med</ISOAbbreviation>
      </Journal>
      <ArticleTitle>Formate assay in body fluids: application in methanol poisoning.</ArticleTitle>
      <AuthorList CompleteYN="Y">
        <Author ValidYN="Y">
          <LastName>Makar</LastName>
          <ForeName>A B</ForeName>
          <Initials>AB</Initials>
        </Author>
        <Author ValidYN="Y">
          <LastName>McMartin</LastName>
          <ForeName>K E</ForeName>
          <Initials>KE</Initials>
        </Author>
        <Author ValidYN="Y">
          <LastName>Palese</LastName>
          <ForeName>M</ForeName>
          <Initials>M</Initials>
        </Author>
        <Author ValidYN="Y">
          <LastName>Tephly</LastName>
          <ForeName>T R</ForeName>
          <Initials>TR</Initials>
        </Author>
      </AuthorList>
    </PubDetails>
  </Article>
</Publications>
